# Generated by Django 3.2 on 2021-09-23 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField()),
                ('booking_duration', models.PositiveSmallIntegerField(choices=[(0, 'All day'), (30, '½ hour'), (60, '1 hour'), (90, '1 ½ hours'), (120, '2 hours'), (150, '2 ½ hours'), (180, '3 hours'), (210, '3 ½ hours'), (240, '4 hours')], default=120)),
                ('min_party_num', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1)),
                ('max_party_num', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], default=6)),
                ('early_booking', models.PositiveSmallIntegerField(choices=[(1, 'From 1 day in advance'), (2, 'From 2 days in advance'), (3, 'From 3 days in advance'), (4, 'From 4 days in advance'), (5, 'From 5 days in advance'), (6, 'From 6 days in advance'), (7, 'From 7 days in advance'), (14, 'From 14 days in advance'), (30, 'From 30 days in advance'), (90, 'From 90 days in advance'), (180, 'From 180 days in advance')], default=90)),
                ('last_booking', models.PositiveSmallIntegerField(choices=[(15, 'At least 15 minutes in advance'), (30, 'At least 30 minutes in advance'), (45, 'At least 45 minutes in advance'), (60, 'At least 1 hour in advance'), (120, 'At least 2 hour in advance'), (180, 'At least 3 hour in advance'), (240, 'At least 4 hour in advance'), (1440, 'At least 24 day in advance'), (1, 'From at least the day before'), (2, 'From at least 2 days before'), (3, 'From at least 3 days before')], default=1)),
                ('booking_time_before_closing', models.PositiveSmallIntegerField(choices=[(15, '15 minutes before closing'), (30, '30 minutes before closing'), (45, '45 minutes before closing'), (60, '1 hour before closing'), (90, '1 ½ hours before closing'), (120, '2 hours before closing')], default=60)),
                ('upward_scaling_policy', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2)),
                ('site_logo', models.ImageField(blank=True, upload_to='sites')),
                ('mon_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('mon_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('tue_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('tue_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('wed_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('wed_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('thu_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('thu_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('fri_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('fri_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('sat_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('sat_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('sun_opening_hour', models.TimeField(default=datetime.time(12, 0))),
                ('sun_closing_hour', models.TimeField(default=datetime.time(23, 0))),
                ('admin_notification_email', models.EmailField(default='your@email.com', max_length=254)),
                ('send_admin_notification_email', models.BooleanField(default=True)),
                ('email_reminder_time', models.PositiveSmallIntegerField(choices=[(0, 'No email reminder'), (24, '24 hours before booking'), (48, '48 hours before booking'), (72, '72 hours before booking')], default=24)),
                ('client_email_booking_created_subject', models.CharField(default='Your booking has been confirmed', max_length=200)),
                ('client_email_booking_created_content', models.TextField(default='\nHi {{ client_name }},\n\nYour booking request has been <strong>confirmed</strong>. We look forward to seeing you soon.\n\n<strong>Your booking:</strong>\nName: {{ client_name }}\nEmail: {{ client_email }}\nParty: {{ party }}\nDate: {{ date }} [{{ duration }}]\nLocation: {{ site_name }}\nReference: {{ reference }}\n')),
                ('client_email_booking_updated_subject', models.CharField(default='Your booking has been updated', max_length=200)),
                ('client_email_booking_updated_content', models.TextField(default='\nHi {{ client_name }},\n\nYour booking has been <strong>updated</strong>. We look forward to seeing you soon.\n\n<strong>Your updated booking:</strong>\nName: {{ client_name }}\nEmail: {{ client_email }}\nParty: {{ party }}\nDate: {{ date }} [{{ duration }}]\nLocation: {{ site_name }}\nReference: {{ reference }}\n')),
                ('client_email_booking_cancelled_subject', models.CharField(default='Your booking has been cancelled', max_length=200)),
                ('client_email_booking_cancelled_content', models.TextField(default='\nHi {{ client_name }},\n\nSorry, we could not accommodate your booking request.\n\n<strong>Your cancelled booking:</strong>\nName: {{ client_name }}\nEmail: {{ client_email }}\nParty: {{ party }}\nDate: {{ date }} [{{ duration }}]\nLocation: {{ site_name }}\nReference: {{ reference }}\n')),
                ('client_email_booking_reminder_subject', models.CharField(default='Your upcoming booking', max_length=200)),
                ('client_email_booking_reminder_content', models.TextField(default='\nHi {{ client_name }},\n\nWe look forward to seeing you soon.\n\n<strong>Your booking:</strong>\nName: {{ client_name }}\nEmail: {{ client_email }}\nParty: {{ party }}\nDate: {{ date }} [{{ duration }}]\nLocation: {{ site_name }}\nReference: {{ reference }}\n')),
                ('admin_email_booking_created_subject', models.CharField(default='New booking', max_length=200)),
                ('admin_email_booking_created_content', models.TextField(default='\n<strong>A new booking has been created:</strong>\nName: {{ client_name }}\nEmail: {{ client_email }}\nParty: {{ party }}\nDate: {{ date }} [{{ duration }}]\nLocation: {{ site_name }}\nReference: {{ reference }}\n')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=150)),
                ('number_of_seats', models.PositiveSmallIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='sites.site')),
            ],
        ),
    ]
