# Generated by Django 3.2 on 2021-09-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=5, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled')], default=1)),
                ('booking_date', models.DateTimeField()),
                ('party', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('duration', models.PositiveSmallIntegerField(choices=[(0, 'All day'), (30, '½ hour'), (60, '1 hour'), (90, '1 ½ hours'), (120, '2 hours'), (150, '2 ½ hours'), (180, '3 hours'), (210, '3 ½ hours'), (240, '4 hours')])),
                ('booking_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTableRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.table')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sites.site'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tables',
            field=models.ManyToManyField(through='bookings.BookingTableRelationship', to='sites.Table'),
        ),
    ]
